name       : python-anyio
version    : 3.7.1
release    : 3
source     :
    - https://files.pythonhosted.org/packages/source/a/anyio/anyio-3.7.1.tar.gz : 44a3c9aba0f5defa43261a8b3efb97891f2bd7d804e0e1f56419befa1adfc780
homepage   : https://github.com/agronholm/anyio
license    : MIT
component  : programming.python
summary    : High level compatibility layer for multiple asynchronous event loop implementations
description: |
    AnyIO is an asynchronous networking and concurrency library that works on top of either asyncio or trio. It implements trio-like structured concurrency (SC) on top of asyncio and works in harmony with the native SC of trio itself.
builddeps  :
    - python-build
    - python-installer
    - python-setuptools-scm
    - python-wheel
rundeps    :
    - python-exceptiongroup
    - python-idna
    - python-sniffio
build      : |
    %python3_setup
install    : |
    %python3_install
