name       : python-anyio
version    : 3.6.2
release    : 2
source     :
    - https://files.pythonhosted.org/packages/source/a/anyio/anyio-3.6.2.tar.gz : 25ea0d673ae30af41a0c442f81cf3b38c7e79fdc7b60335a4c14e05eb0947421
homepage   : https://github.com/agronholm/anyio
license    : MIT
component  : programming.python
summary    : High level compatibility layer for multiple asynchronous event loop implementations
description: |
    AnyIO is an asynchronous networking and concurrency library that works on top of either asyncio or trio. It implements trio-like structured concurrency (SC) on top of asyncio and works in harmony with the native SC of trio itself.
builddeps  :
    - python-setuptools-scm
rundeps    :
    - python-idna
    - python-sniffio
build      : |
    %python3_setup
install    : |
    %python3_install
